### ISSUE TITLE
Incorrect number of docs retrieved on table scan with filter

### ISSUE THREAD

**Issue by dpkshrma** [automategreen/dynamoose#111]
**How to replicate the issue?**
*Model name*: Vehicles
*Table count*: 50 rows where first 4 aren't registered
*Query*:
```js
Vehicles
  .scan({
    registered: {
     eq: true
    }
  })
  .limit(10)
  exec()
  .then((items) => {
    console.log(items.length); // 6
  });
```

Should the number of docs returned not be 10 here since 46 docs match the filter? Please let me know if I am doing something wrong here.

**Comment by brandongoode** [comment]
limit is applied before filters.   It's just how DynamoDB works.  It scans the first 10 items then filters the matches.

**Comment by derit** [comment]
any solution ? if we need 10 limit with scan equals and result is limit 10 ?

**Comment by dolsem** [comment]
@derit there's no solution, because functionality is not supported by DynamoDB. There are, however, 3 workarounds I can think of: 1) Use sparse indexes instead of filters and query them instead, 2) Do not use limit option, get all data you can get from DynamoDB, truncate your results (obviously very expensive), 3) Use DynamoDB Streams to mirror your data to another datastore, more suitable for this type of query (e.g. ElasticSearch cluster).

**Comment by derit** [comment]
@dolsem this is good reference for this issue
[https://stackoverflow.com/a/47768751](https://stackoverflow.com/a/47768751)

**Comment by dolsem** [comment]
@derit yes, if you're fine with multiple read operations instead of one, this is a good option too.

**Comment by dolsem** [comment]
Perhaps someone should build a pagination plugin that implements this.
