### ISSUE TITLE
Create "map" attribute with unknown types

### ISSUE THREAD

**Issue by kjprice** [automategreen/dynamoose#146]
Similarly to how we are now able to create attributes "on the fly", without having to define them in a schema; it would be nice to be able to create objects "dynamo maps" whose sub-attributes will be automatically computed.

Currently, if I try create a `map` type attribute (which is not already defined in the schema), it gets saved as type "S" and the object gets stringified.

So, assuming we have a schema setup for this `obj`:

```js
obj = {
   id: '123',
   properties: {
      name: 'bob'
   }
}
```

When ran as `schema.toDynamo(obj)`, with `saveUnknown` option set to `true`, we would get:

```js
{
   id: { S: '123' },
   properties: { S: '{"name":"bob"}'} // `string`
}
```

It might be preferable to expect something like this instead:
```js
{
   id: { S: '123' },
   properties: {
      // `map` type
      M: { 
         S: { name: 'bob' }
      }
   }
}
```

**Comment by brandongoode** [comment]
Haven't had time to check, but what happens if you set both `saveUnknown` and `useDocumentTypes` to `true`?

```js
var schema = new Schema({...}, {
  saveUnknown: true ,
  useDocumentTypes: true 
});
```

**Comment by kjprice** [comment]
The same thing. A string is created with the stringified JSON.

**Comment by brandongoode** [comment]
@kjprice Thanks for trying.

Probably need to create an option at the attribute and schema levels to control the behavior.

**Comment by treyhuffine** [comment]
I think I'm running into a similar issue. I'm not able to declare an attribute using the generic `Object`. It gets blocked on this line https://github.com/automategreen/dynamoose/blob/master/lib/Attribute.js#L161 since the `typeVal` is the constructor function.

Side note, huge thanks for building and maintaining this library @brandongoode

**Comment by brandongoode** [comment]
@treyhuffine could you provide an example?   It shouldn't block it.  It should just `JSON.stringify` and save it as a `String`.

**Comment by treyhuffine** [comment]
@brandongoode sorry I didn't explain that well. Based on that code construction, you can't declare an attribute as `Object` and still use the native `Map` data type. Since `typeof Object === 'function'`, an object literal is required or the `JSON.stringify` will be used. The functionality I was hoping for would be declaring an attribute as an `Object` to use `Map` an then filling in the properties without needing to declare them.

**Comment by brandongoode** [comment]
@treyhuffine -- Thanks for clarifying.  Yes, that's the same issue.  It's on the todo list to add this functionality.

**Comment by ro-savage** [comment]
Same issue. Can't `read` or `write` DynamoDB Map type objects that contain unknown keys / that aren't specified in the Schema.

Looking forward to v.0.9.0. Thanks hardwork Brandon!

```js
// Expected returned object
{ 
id: 'person-Id-1',
name: 'John',
tickets: {
  'random-Id-1': {
    id: 'random-Id-1',
    event: 'eventId1'
  },
  'random-Id-2': {
    id: 'random-Id-2',
    event: 'event-Id-1'
  }
}


// Expected Schema
const personSchema = new Schema({
  id: { type: String, hasKey: true },
  name: String,
  tickets: 'map'
}, {
  useDocumentTypes: true,
  saveUnknown: true,
})
```

p.s. I found it hard to understand how to use the DynamoDB's Map in the scheme. If I was meant to use type of `Map`, `'Map'` or `'map'`, or `Object`

**Comment by sickDevelopers** [comment]
Hello everyone, is anybody working on this right now? I think it's a blocking issue for many

**Comment by alessiodezotti** [comment]
+1

**Comment by brandongoode** [comment]
#240 adds this functionality.
