### ISSUE TITLE
Dynamic Capacity And Automated Updates

### ISSUE THREAD

**Issue by bbqbaron** [automategreen/dynamoose#172]
Dynamo seems to recommend, and is increasingly adopting, the notion that table capacity should be dynamic (for instance, they've added [autoscaling](https://aws.amazon.com/blogs/aws/auto-scale-dynamodb-with-dynamic-dynamodb/) recently). Dynamoose seems to treat its throughput settings as non-negotiable: if, for instance, an index already exists but with different capacity, it tries to create a new one.

I'm curious about your thoughts here. Would it be all right to PR a change that that defers on capacity, such that if an index of the right name and type (and maybe other attributes?) exists, it accepts the index as existing, and only uses capacity settings when _creating_? That fits our particular use case much better, but I don't know how it fits in with your plans.

**Comment by lrcry** [comment]
@bbqbaron  Just wondering how it works if we set `create: false` when we define the schema? Will it still create new indices?

**Comment by bbqbaron** [comment]
It probably won't, but we do want it to create new indices IFF they don't exist--but excluding capacity from the equality check. Since Dynamo is embracing dynamic capacity, having capacity as a fixed quantity in your code base seems like it might be more and more of a problem. That's only my opinion, of course! But, if it doesn't change, we simply won't be able to use Dynamoose to manage our Dynamo tables and will need to roll our own solution.

**Comment by troyswanson** [comment]
IMO the management of tables shouldn't be handled by Dynamoose, but that's my opinion.

CloudFormation is specifically designed to manage AWS resources -- this project should advocate for the use of that instead (again, IMO).

**Comment by brandongoode** [comment]
The throughput is only used for the initial creation of the tables. It is expected that the capacity will be variable.

@troyswanson -  I agree CloudFormation is the best way to manage anything in AWS. I would like to figure out a clean way to create one from the schema. See #151.

**Comment by bbqbaron** [comment]
@brandongoode Sorry for the delay, but although you're right that tables seem to ignore capacity, I think indices don't (see index comparison code [here](https://github.com/automategreen/dynamoose/blob/master/lib/Table.js#L40)). Is this also intended?

**Comment by ricxsar** [comment]
Hi all, I would like to request this functionality for the application I am developing.

I am developing an vehicle monitoring system which dealing with time series data. I design the app to auto create tables at the start of the month so that the data will be grouped per month. The reason behind this design is to make old data easier to backup on s3. I have read that it is also recommended to `read and drop` the table than `read and delete` when doing backup since it doesn't consumed too much capacity units and it doesn't affect the new data. It is also beneficial for us in this way since the introduction of the `DynamoDB Backup Feature` where we're going to backup and drop the table. Unfortunately, the region we are working on doesn't support the feature as of the moment.

I would like the created table to be defaulted to auto scaling where we don't need to manually change it's  allocated capacity units everytime. Please consider.

Thanks.

PS: Thank you for developing this wonderful library.

**Comment by lengk** [comment]
@ricxsar bump

**Comment by ricxsar** [comment]
@lengk  Do you have any plans on implementing this one? It is greatly appreciated.

**Comment by fishcharlie** [comment]
If anyone would like to create a PR for this I’d be more than happy to review it and consider merging it in.
