### ISSUE TITLE
Typescript: model() does not return a very useful type

### ISSUE THREAD

**Issue by sgtoj** [automategreen/dynamoose#233]
Is possible this input generic types are incorrect? ~~I believe it should only have a single generic type for input. Furthermore, that type can/should be inferred from the `schema` parameter.~~ I pose this question because `.model()` is returning is returning a type of `ModelConstructor<{}, {}, Model<{}>>` . 

https://github.com/automategreen/dynamoose/blob/d4a3ad66329852fc5e400e961d75a027b90eb03d/dynamoose.d.ts#L8-L12

### Example 

~~Here is an example code test.~~ Although this code block is incorrect (e.g. missing typing), the over original issue remain: an type error was thrown when passing three types to `model()`. 

```js
import * as dynamoose from "dynamoose";

const timelogSchema = new dynamoose.Schema({
        issueid: { type: Number, hashKey: true },
        entries: { type: Object }
    }, {
        useDocumentTypes: true
    }
);

let model = {
    issueid: 7,
    entries: {
        "123": {start: 0 }
    }
};

(async () => {
    const Timelog = dynamoose.model("timelog", timelogSchema);
    // Timelog is ModelConstructor<{}, {}, Model<{}>>
    //    why the empty objects?
    let timelog = new Timelog(model);
    // timelog is Model<{}>
    //   this is because Timelog has the wrong type
    await timelog.save();
})();
```

**Comment by brandongoode** [comment]
That's for troubleshooting this and the improvement.

**Comment by sahilchaddha** [comment]
Hey,

I have just started with Typescript and I am trying to integrate Dynamoose for my Typescript Application.

I am unable to access model properties, since typescript gives me error.
I understand that in need to create my own interface to access the values but i am unable to understand how can i convert the Model<{}> to my Custom Interface. 

`var userSchema = new dynamoose.Schema({
        username: {
            type: String,
            hashKey: true
        },
        password: {
            type: String
        },
        email: {
            type: String
        },
        access_level: {
            type: String
        }
    }, {
        useNativeBooleans: true,
        useDocumentTypes: true
    })

export default dynamoose.model('User', userSchema)`



`          User.queryOne("username").eq(reqPayload.username).exec(function (err, user) {
                  console.log(user.username)
              })
          })`

returns Compile Error for typescript 
`error TS2339: Property 'username' does not exist on type 'Model<{}>'`
>
