### ISSUE TITLE
.select

### ISSUE THREAD

**Issue by elgubenis** [automategreen/dynamoose#36]
are there any plans on writing a .select method? like the .select form mongoose, do you have any workaround for that? @brandongoode, since im using dynamoose with lambda it would be really cool to to use as less memory as possible, so when i fetch 100 objects but just want certain keys of every item, is that even possible with dynamodb?

**Comment by brandongoode** [comment]
The dynamoDB equivalent to select is to list the attributes to get (http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-AttributesToGet).  This is done with the `attributes` query option,  https://github.com/automategreen/dynamoose#queryattributesattributes.  It is an array of the names of the attributes you want returned.

Also, since you're using Lambda,  I would recommend disabling create and waitForActive.  The will greatly reduce the lambda execution time. This is what I do for my lambda's:

```js
dynamoose.setDefaults({create: false, waitForActive: false});
```

**Comment by elgubenis** [comment]
should've read your documentation more carefully, sorry, thank you also for your recommendation. dynamoose doesn't (yet) support nested schemas, is that correct?
something like:
```js
const elementSchema = new Schema({
  type: String,
  width: Number,
  height: Number,
  content: String,
  x: Number,
  y: Number,
});

const pageSchema = new Schema({
  elements: [elementSchema],
  width: Number,
  height: Number,
});
```

**Comment by brandongoode** [comment]
That's correct -- no nested schema support.
